# Generated by Django 5.2.9 on 2026-02-01 05:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HOUSKI Climbing Club', max_length=200)),
                ('description', models.TextField(help_text='Main club description')),
                ('history', models.TextField(blank=True, help_text='Club history and achievements')),
                ('founded_year', models.IntegerField(default=2000)),
                ('location', models.CharField(default='Pilsen, Czech Republic', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Club Information',
                'verbose_name_plural': 'Club Information',
            },
        ),
        migrations.CreateModel(
            name='PictureOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload picture of the week', upload_to='potw/')),
                ('caption', models.CharField(max_length=200)),
                ('photographer', models.CharField(blank=True, help_text='Photographer name', max_length=100)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Only one picture can be active at a time')),
            ],
            options={
                'verbose_name': 'Picture of the Week',
                'verbose_name_plural': 'Pictures of the Week',
                'ordering': ['-date_added'],
            },
        ),
    ]
